export const UPDATE_POSTS = "UPDATE_POSTS";
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_LOGGED_IN_USER = "UPDATE_LOGGED_IN_USER";
export const DELETE_A_POST = "DELETE_A_POST";
